
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; 

CREATE SMALLFILE TABLESPACE BET_ITM
DATAFILE 'TALLER1' SIZE 512 M,
'TALLER2' SIZE 512 M;
 
CREATE BIGFILE TABLESPACE BET_AUDITING
DATAFILE 'BIG_AUDITING.DBF' SIZE 2G;

CREATE UNDO TABLESPACE UNDOBET
DATAFILE 'UNDO_FILE_BET.DBF'
SIZE 500 M
AUTOEXTEND ON;

CREATE PROFILE DEVELOPER LIMIT  
    PASSWORD_LIFE_TIME 90
    CONNECT_TIME 60
    SESSIONS_PER_USER 1 
    IDLE_TIME 30 
    FAILED_LOGIN_ATTEMPTS 5;   
    
    
CREATE PROFILE WEB_APPLICATION LIMIT  
    PASSWORD_LIFE_TIME 30
    CONNECT_TIME UNLIMITED 
    SESSIONS_PER_USER 5
    IDLE_TIME UNLIMITED  
    FAILED_LOGIN_ATTEMPTS 2;   
    
    
    
CREATE PROFILE DBA_ADMIN LIMIT  
    SESSIONS_PER_USER 1
    CONNECT_TIME 30 
    IDLE_TIME UNLIMITED  
    FAILED_LOGIN_ATTEMPTS 2
    PASSWORD_LIFE_TIME 30;   
    
    
CREATE PROFILE ANALYST LIMIT  
    SESSIONS_PER_USER 1
    CONNECT_TIME 30 
    IDLE_TIME 5  
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 30
    PASSWORD_GRACE_TIME 3;
    
    
CREATE PROFILE SUPPORT_III LIMIT  
    SESSIONS_PER_USER 1
    CONNECT_TIME 240 
    IDLE_TIME 5  
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 20
    PASSWORD_GRACE_TIME 3;
    
    
    
CREATE PROFILE REPORTER LIMIT  
    SESSIONS_PER_USER 1
    CONNECT_TIME 90 
    IDLE_TIME 15  
    FAILED_LOGIN_ATTEMPTS 4
    PASSWORD_LIFE_TIME UNLIMITED 
    PASSWORD_GRACE_TIME 5;
    
  
CREATE PROFILE AUDITOR LIMIT  
    SESSIONS_PER_USER 1
    CONNECT_TIME 90 
    IDLE_TIME 15  
    FAILED_LOGIN_ATTEMPTS 4
    PASSWORD_LIFE_TIME UNLIMITED 
    PASSWORD_GRACE_TIME 5;
    
    
  CREATE USER DEV_YONERIC
    IDENTIFIED BY yoneric
    PROFILE DEVELOPER;
    
  CREATE USER WEB_RONALD
    IDENTIFIED BY ronald
    PROFILE WEB_APPLICATION;
    
  
    CREATE USER DBA_JULIAN
    IDENTIFIED BY julian
    PROFILE DBA_ADMIN;
    
    
    CREATE USER ANLY_EDISSON
    IDENTIFIED BY edisson
    PROFILE ANALYST;
    
    CREATE USER SP3_KATE
    IDENTIFIED BY kate
    PROFILE SUPPORT_III;
    
    CREATE USER RPT_BRIAN
    IDENTIFIED BY brian
    PROFILE REPORTER;
    
    
    CREATE USER AUD_SANTIAGO
    IDENTIFIED BY santiago
    PROFILE AUDITOR;

    
   CREATE USER DEV_SERGIO
    identified by sergio
    PROFILE DEVELOPER;
    
    
   CREATE USER DBA_ANDRES
    IDENTIFIED BY andres
    PROFILE DBA_ADMIN;
    
    
   CREATE USER WEB_MACARENA
    IDENTIFIED BY macarena
    PROFILE WEB_APPLICATION;
    
 SELECT * FROM DBA_DATA_FILES;
 
CREATE TABLE USUARIOS (
 ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL, 
 DOCUMENTO NUMERIC NOT NULL,
 TIPO_DOCUMENTO VARCHAR2 (255) NOT NULL,
 LUGAR_EXPEDICION VARCHAR2(255)NOT NULL ,
 FECHA_EXPEDICION DATE NOT NULL,
 NACIONALIDAD VARCHAR2 (255) NOT NULL,
 PRIMER_NOMBRE VARCHAR2(255) NOT NULL,
 SEGUNDO_NOMBRE VARCHAR2 (255),
 PRIMER_APELLIDO VARCHAR2 (255) NOT NULL,
 SEGUNDO_APELLIDO VARCHAR2 (255),
 FECHA_DE_NACIMIENTO DATE,
 LUGAR_NACIMIENTO VARCHAR2 (255) NOT NULL,
 DICRECCION VARCHAR2 (255) NOT NULL,
 DIRECCION2 VARCHAR (255),
 CONTRASENA VARCHAR2 (255) NOT NULL,
 EMAIL VARCHAR2 (255) NOT NULL,
 IDIOMA_EMAIL VARCHAR2 (255) NOT NULL,
 CELULAR NUMERIC,
 TERMINOS NUMERIC NOT NULL CHECK (TERMINOS IN (0,1)),
 RECIBIR_INFO NUMERIC NOT NULL CHECK (RECIBIR_INFO IN (0,1)), 
 TITULO VARCHAR2 (20) NOT NULL,
 RUTA_DOCUMENTOS VARCHAR2 (255),
 SOFT_DELETION NUMERIC NOT NULL CHECK (SOFT_DELETION IN (0,1)),
 CUENTA_BANCARIA VARCHAR2(255),
 SALDO NUMERIC NOT NULL,
 ID_MUNICIPIO NUMERIC NOT NULL,
 ID_PREFIJO NUMERIC NOT NULL,
 ID_LIMITE NUMERIC NOT NULL,
 ID_BONO NUMERIC NOT NULL,
 ID_APUESTA NUMERIC NOT NULL
 )
 TABLESPACE BET_ITM;

 CREATE TABLE PAISES (
 ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL, 
 PAIS VARCHAR2(255)
 )
 TABLESPACE BET_ITM;
 
 CREATE TABLE MUNICIPIOS(
 ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
 MUNICIPIO VARCHAR2(255),
 ID_DEPARTAMENTO NUMERIC NOT NULL)
 TABLESPACE BET_ITM;
 
 
 CREATE TABLE PREFIJOS(
 ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
 PREFIJO VARCHAR2 (50) NULL
 )
 TABLESPACE BET_ITM;
 
 
 CREATE TABLE DEPARTAMENTOS(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
DEPARTAMENTO VARCHAR (255) NOT NULL,
ID_PAIS NUMERIC NOT NULL
)
TABLESPACE BET_ITM;

CREATE TABLE LIMITES(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
LIMITE_DIA NUMERIC,
LIMITE_SEMANA NUMERIC,
LIMITE_AÑO NUMERIC
)
TABLESPACE BET_ITM;


CREATE TABLE BONOS(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
CODIGO_BONO VARCHAR2(50),
FECHA_INICIO DATE,
FECHA_FIN DATE,
ESTADO VARCHAR2(20)
)
TABLESPACE BET_ITM;


CREATE TABLE APUESTAS(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
ID_USUARIO NUMERIC,
VALOR_APOSTADO NUMERIC,
FECHA DATE,
ID_DETALLE NUMERIC,
ID_ESTADO NUMERIC
)
TABLESPACE BET_ITM;


CREATE TABLE PARTIDOS(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
ID_LOCAL NUMERIC NOT NULL,
ID_VISITANTE NUMERIC NIT NULL,
GOLES_L NUMERIC NOT NULL,
GOLES_V NUMERIC NOT NULL,
ID_GANADOR_PT NUMERIC,
ID_GANADOR_ST NUMERIC,
ESTADO VARCHAR2 (255), NOT NULL,
FECHA DATE
)
TABLESPACE BET_ITM;


CREATE TABLE EQUIPOS(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
EQUIPO VARCHAR(255) NOT NULL
)
TABLESPACE BET_ITM;

CREATE TABLE DETALLES_APUESTAS(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
ID_PARTIDO NUMERIC NOT NULL,
ID_APUESTA NUMERIC NOT NULL,
ID_CUOTA NUMERIC NOT NULL,
OPCION_CUOTA NUMERIC NOT NULL CHECK(OPCION_CUOTA >=1 AND OPCION_CUOTA<=3)
)
TABLESPACE BET_ITM;


CREATE TABLE CUOTAS(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
ID_PARTIDO NUMERIC NOT NULL,
DESCRIPCION_CUOTA VARCHAR2(255) NOT NULL,
OPCION1 VARCHAR2 (255),
OPCION2 VARCHAR2 (255),
OPCION3 VARCHAR2 (255)
)
TABLESPACE BET_ITM;


CREATE TABLE PREFERENCIAS(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
DESCRIPCION VARCHAR2 (255)NOT NULL
)
TABLESPACE BET_ITM;


CREATE TABLE PREFERENCIAS_DE_USUARIOS(
ID_USUARIO NUMERIC  NOT NULL,
ID_PREFERENCIA NUMERIC  NOT NULL,
PRIMARY KEY ( ID_USUARIO,ID_PREFERENCIA)
)
TABLESPACE BET_ITM;

CREATE TABLE ESTADOS(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
ESTADO VARCHAR2(255) NOT NULL
)
TABLESPACE BET_ITM;

CREATE TABLE RETIROS(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
FECHA_SOLICITUD TIMESTAMP NOT NULL,
FECHA_DESEMBOLSO TIMESTAMP NOT NULL,
BANCO VARCHAR2(255),
CUENTA_BANCARIA VARCHAR2(255),
REQUISITO NUMERIC CHECK (REQUISITO IN (0,1)) NOT NULL,
ID_USUARIO NUMERIC NOT NULL,
ID_COMPROBANTE NUMERIC NOT NULL
)
TABLESPACE BET_ITM;

CREATE TABLE DEPOSITOS(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
VALOR NUMERIC NOT NULL,
FECHA TIMESTAMP NOT NULL,
ID_USUARIO NUMERIC NOT NULL,
ID_ESTADO NUMERIC NOT NULL
)
TABLESPACE BET_ITM;


CREATE TABLE ESTADOS_DEPOSITOS(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
ESTADO VARCHAR2 (255) NOT NULL
)
TABLESPACE BET_ITM;


CREATE TABLE MEDIOS_DE_PAGO(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
MEDIO_DE_PAGO VARCHAR2(255) NOT NULL,
VALOR_MINIMO NUMERIC NOT NULL,
VALOR_MAXIMO NUMERIC NOT NULL,
ID_DEPOSITOS NUMERIC NOT NULL
)
TABLESPACE BET_ITM;

CREATE TABLE COMPROBANTES(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
FACTURA_SERVICIOS VARCHAR2(255) NOT NULL,
TAMANO_FACTURA_SERVICIOS VARCHAR2(255) NOT NULL,
EXTENSION_FACTURA_SERVICIOS VARCHAR2(255) NOT NULL,
COMPROBANTE_DEPOSITO VARCHAR2(255) NOT NULL,
TAMANO_COMPROBANTE_DEPOSITO VARCHAR2(255) NOT NULL,
EXTENSION_COMPROBANTE_DEPOSITO VARCHAR2(255) NOT NULL,
IDENTIFICACION VARCHAR2(255) NOT NULL,
TAMANO_IDENTIFICACION VARCHAR2(255) NOT NULL,
EXTENSION_IDENTIFICACION VARCHAR2(255) NOT NULL,
FOTO_PERSONAL VARCHAR2(255) NOT NULL,
TAMANO_FOTO_PERSONAL VARCHAR2(255) NOT NULL,
EXTENSION_FOTO_PERSONAL VARCHAR2(255) NOT NULL,
ID_RETIROS NUMERIC NOT NULL
)
TABLESPACE BET_ITM;

CREATE TABLE AUDITORIA(
ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
DATE_AND_TIME TIMESTAMP NOT NULL,
TABLA VARCHAR2(255),
RECORD_ID NUMERIC NOT NULL,
ACTION VARCHAR2 (255)  NOT NULL,
USUARIO VARCHAR2 (255)  NOT NULL,
IP VARCHAR2 (20)
)
TABLESPACE BET_AUDITING;


 